image: ubuntu:devel

pages:
  script:
    - apt update
    - apt install --yes pandoc
    - mkdir -p public
    - cp style.css public/
    - date >> README.md
    - pandoc --css=style.css --standalone --highlight-style tango posts/tools.md -o public/index.html

  artifacts:
    paths:
      - public
