Build:
  image: ubuntu:devel
  stage: build
  script: cat /etc/os-release

website:
  stage: deploy
  trigger: germs-dev/deanturpin
  only: [main]

cv:
  stage: deploy
  trigger: germs-dev/cv
  only: [main]

